apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: dsunitha2/final_backend:latest
        name: backend
        ports:
        - containerPort: 8706
          name: backend
        env:
          - name: PORT
            value: "8706"
          - name: DATABASE_URI
            value: "mongodb://root:example@mongodb:27017/"
          - name: REDIS_HOST
            value: "redis"
          - name: REDIS_PASSWORD
            value: "someredispassword"