apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
spec:
  ports:
  - name: "backend-service"
    port: 8706
    targetPort: 8706
  selector:
    app: backend
  type: LoadBalancer