name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This means deploy will run after build completes successfully.

    steps:
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Updating the EKS cluster using kubeconfig
      run: aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name sun_cluster
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 

    - name: Copying the key pair from GitHub secrets to the EC2 instance
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_KEY_PAIR }}" > ~/.ssh/sun_KP.pem
        chmod 400 ~/.ssh/sun_KP.pem

    - name: Add EC2 instance to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

    - name: Clone the repo
      run: |
        ssh -i ~/.ssh/sun_KP.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          if [ -d "devops-final-project-ih" ]; then
            rm -rf devops-final-project-ih
          fi
          git clone https://github.com/Sunithadodda/devops-final-project-ih.git
        EOF

    - name: Setup kubectl
      run: |
        ssh -i ~/.ssh/sun_KP.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          # Install kubectl if not already installed
          if ! command -v kubectl &> /dev/null; then
            echo "Installing kubectl..."
            curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
          else
            echo "kubectl is already installed."
          fi
        EOF
    - name: Deploy manifests to EKS
      run: |

        ssh -i ~/.ssh/sun_KP.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          cd devops-final-project-ih/kubernetes_manifest_files || exit 1  # Change into the cloned directory
          ls
        
          #cd kubernetes_manifest_files || exit 1  # Change into the cloned directory
          kubectl apply -f ./backend-deployment.yml 
          kubectl apply -f ./backend-service.yml 
          kubectl apply -f database-deployment.yml --validate=false
          kubectl apply -f database-service.yml --validate=false
          kubectl apply -f database-pv.yml --validate=false
          kubectl apply -f database-pvc.yml --validate=false
          kubectl apply -f frontend-deployment.yml --validate=false
          kubectl apply -f frontend-service.yml --validate=false
          kubectl apply -f redis-deployment.yml --validate=false
          kubectl apply -f redis-service.yml --validate=false
          kubectl apply -f redis-pv.yml --validate=false
          kubectl apply -f redis-pvc.yml --validate=false
        EOF
